/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ProductCollectionsDAO;
import dao.ProductDAO;
import dao.ProductJdbcDAO;
import domain.Product;
import helpers.SimpleListModel;
import java.util.Collection;
import static java.util.Locale.filter;
import static java.util.Locale.filter;
import javax.swing.JOptionPane;

/**
 *
 * @author ksts
 */
public class ProductViewer extends javax.swing.JDialog {

    public static ProductDAO dao;
    SimpleListModel productsModel = new SimpleListModel();
    SimpleListModel categoriesModel = new SimpleListModel();

    /**
     * Creates new form ProductViewer
     */
    public ProductViewer(java.awt.Frame parent, boolean modal, ProductDAO daoIn) {
        super(parent, modal);
        initComponents();
        dao = daoIn;
        Collection<Product> products = dao.getProducts();
        productsModel.updateItems(products);
        itemList.setModel(productsModel);
        CmbCategoryFilter.setEditable(true);
        Collection<String> category = dao.getCategories();
        categoriesModel.updateItems(category);
        CmbCategoryFilter.setModel(categoriesModel);
        itemList.setName("itemList");
        DeleteButtonProductViewer.setName("deleteButton");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList<>();
        CloseButtonProductViewer = new javax.swing.JButton();
        DeleteButtonProductViewer = new javax.swing.JButton();
        TxtSearchById = new javax.swing.JTextField();
        SearchByIDlabel = new javax.swing.JLabel();
        ButtonSearchById = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CmbCategoryFilter = new javax.swing.JComboBox<>();
        EditButtonProductViewer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(itemList);

        CloseButtonProductViewer.setText("Close");
        CloseButtonProductViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonProductViewerActionPerformed(evt);
            }
        });

        DeleteButtonProductViewer.setText("Delete");
        DeleteButtonProductViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonProductViewerActionPerformed(evt);
            }
        });

        SearchByIDlabel.setText("Search By Id:");

        ButtonSearchById.setText("Search");
        ButtonSearchById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchByIdActionPerformed(evt);
            }
        });

        jLabel1.setText("Category Filter:");

        CmbCategoryFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbCategoryFilterActionPerformed(evt);
            }
        });

        EditButtonProductViewer.setText("Edit");
        EditButtonProductViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonProductViewerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EditButtonProductViewer)
                .addGap(18, 18, 18)
                .addComponent(DeleteButtonProductViewer)
                .addGap(18, 18, 18)
                .addComponent(CloseButtonProductViewer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchByIDlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtSearchById)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonSearchById, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CmbCategoryFilter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSearchById, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchByIDlabel)
                    .addComponent(ButtonSearchById))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CmbCategoryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseButtonProductViewer)
                    .addComponent(DeleteButtonProductViewer)
                    .addComponent(EditButtonProductViewer))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonProductViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonProductViewerActionPerformed
        dispose();
    }//GEN-LAST:event_CloseButtonProductViewerActionPerformed

   private void DeleteButtonProductViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonProductViewerActionPerformed
       //JOptionPane.showMessageDialog(this, "Are you sure you want to delete", "title", JOptionPane.INFORMATION_MESSAGE);
       if (!itemList.isSelectionEmpty()) {

           int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this product?");

// did the user click the yes button?
           if (result == JOptionPane.YES_OPTION) {
               Product product = itemList.getSelectedValue();
               dao.removeProduct(product);
               Collection<Product> products = dao.getProducts();
               productsModel.updateItems(products);
               itemList.clearSelection();
           }
       }

   }//GEN-LAST:event_DeleteButtonProductViewerActionPerformed

    private void ButtonSearchByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchByIdActionPerformed
        String productId = TxtSearchById.getText();
        Product product = dao.searchById(productId);
        productsModel.updateItems(product);
        itemList.setModel(productsModel);
    }//GEN-LAST:event_ButtonSearchByIdActionPerformed

    private void CmbCategoryFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbCategoryFilterActionPerformed
        // TODO add your handling code here:

        String category = (String) CmbCategoryFilter.getSelectedItem();
        Collection<Product> filteredProducts = dao.filterByCategory(category);
        productsModel.updateItems(filteredProducts);
    }//GEN-LAST:event_CmbCategoryFilterActionPerformed

    private void EditButtonProductViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonProductViewerActionPerformed
        Product selectedProduct = itemList.getSelectedValue();

        ProductEditor dialog = new ProductEditor(this, true, selectedProduct, dao);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        productsModel.updateItems(dao.getProducts());
    }//GEN-LAST:event_EditButtonProductViewerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProductViewer dialog = new ProductViewer(new javax.swing.JFrame(), true, dao);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSearchById;
    private javax.swing.JButton CloseButtonProductViewer;
    private javax.swing.JComboBox<String> CmbCategoryFilter;
    private javax.swing.JButton DeleteButtonProductViewer;
    private javax.swing.JButton EditButtonProductViewer;
    private javax.swing.JLabel SearchByIDlabel;
    private javax.swing.JTextField TxtSearchById;
    private javax.swing.JList<domain.Product> itemList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
